//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateDataViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leas
    {
        public short LeaseID { get; set; }
        public short BuildingID { get; set; }
        public short SuiteID { get; set; }
        public string TenantName { get; set; }
        public Nullable<System.DateTime> LeaseBegin { get; set; }
        public Nullable<System.DateTime> LeaseExpiration { get; set; }
        public Nullable<double> RentPerMonth { get; set; }
    
        public virtual Suite Suite { get; set; }
    }
}
