//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateDataViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suite()
        {
            this.Leases = new HashSet<Leas>();
        }
    
        public short SuiteID { get; set; }
        public short BuildingID { get; set; }
        public string SuiteName { get; set; }
        public Nullable<int> SuiteArea { get; set; }
    
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leas> Leases { get; set; }
    }
}
